baseURL       = "https://p2gconnecto.com"
languageCode  = "it"
title         = "P2Gconnecto"
theme         = "roxo"
summarylength = 25

# Site Menus
[menu]
  # Navbar Menus
  [[menu.nav]]
    name    = "Home"
    url     = ""
    weight  = 1
  #[[menu.nav]]
  #  name    = "Chi siamo"
  #  url     = "about"
  #  weight  = 2
  [[menu.nav]]
    name    = "Portfolio"
    url     = "portfolio"
    weight  = 3
  #[[menu.nav]]
  #  name    = "Blog"
  #  url     = "blog"
  #  weight  = 4
  [[menu.nav]]
    name    = "Contattaci"
    url     = "contact"
    weight  = 4

# Site Params
[params]
  logo = "images/logo.png"
  dateFormat = "26 FEB 1994"
  # Meta data
  description = "P2Gconnecto"
  author = "P2Gconnecto"
  # Google Analitycs
  googleAnalitycsID = "Your ID"
  # We're using formspree.io for form handling, paste your formspree url below
  formspreeFormUrl  = "https://formspree.io/myykjpje"

  # Contact Form
  [params.contactForm]
    placeholder_first_name        = "First Name"
    placeholder_last_name         = "Last Name"
    placeholder_email             = "Email"
    placeholder_project_type      = "Project Type"
    placeholder_about_the_project = "About the Project"
    send_message                  = "Send Message"

    [[params.contactForm.projectType]]
      value = "gd"
      title  = "Graphics Design"
    [[params.contactForm.projectType]]
      value = "wd"
      title  = "Web Design"
  
  # Navbar Action Button
  [params.navAction]
    status  = true
    name    = "Get in touch"
    url     = "contact"
  

  # Banner Section
  [params.banner]
    enable                = true
    background_image      = "images/backgrounds/hero-background.jpg"
    heading               = "Progettazione Personalizzazione Realizzazione"
    tagline               = "P2GCONNECTO"
    primary_button        = "I nostri lavori"
    primary_button_url    = "portfolio"
    secondary_button      = "Contattaci"
    secondary_button_url  = "contact"

  [params.portfolio]
    enable    = true
    title     = "I Nostri Progetti Recenti"
    subtitle  = ""

  [params.call_to_action]
    enable              = true
    background_image    = "images/backgrounds/cta-background.jpg"
    title               = "LAVORIAMO INSIEME"
    primary_button      = "Contattaci"
    primary_button_url  = "contact"
    secondary_button    = "Non sei convinto?"
    secondary_button_url = "portfolio"

  [params.footer]
    # Footer Contact Info
    [params.footer.contactInfo]
      title   = "Sede"
      address = "Via Scala di Giuda, 126 - Reggio Calabria, Italia"
      phone   = ""
      email   = ""
      # Footer Sitemap
      [params.footer.sitemap]
        title   = "Sitemap"
        [[params.footer.sitemap.link]]
          name = "Chi Siamo"
          url  = "about"
        [[params.footer.sitemap.link]]
          name = "Progetti"
          url  = "portfolio"
        #[[params.footer.sitemap.link]]
        #  name = "Blog"
        #  url  = "blog"
        [[params.footer.sitemap.link]]
          name = "Contatti"
          url  = "contact"
      # Footer Social Media
      #[params.footer.social]
      #  title   = "Social Media"
      #  [[params.footer.social.link]]
      #    name = "Medium"
      #    url  = "#"
      #  [[params.footer.social.link]]
      #    name = "Behance"
      #    url  = "#"
      #  [[params.footer.social.link]]
      #    name = "Dribbble"
      #    url  = "#"
      #  [[params.footer.social.link]]
      #    name = "Instagram"
      #    url  = "#"
      # Footer Service
      [params.footer.service]
        title       = "Aiutiamo le aziende"
        description = "Costruiamo prodotti migliori per aiutare i nostri clienti a creare aziende migliori"
